---
title: "function_testing"
author: "Isaiah Katz"
date: "2025-07-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(microbenchmark)

source("yield_estimation/bl_cross_estimation.R")

```

```{r}
usa <- read.csv("reconstructed_data/usa-bs.csv")
gbr <- read.csv("reconstructed_data/gbr-bs.csv")
jpn <- read.csv("reconstructed_data/jpn-bs.csv")
cad <- read.csv("reconstructed_data/cad-bs.csv")
ger <- read.csv("reconstructed_data/ger-bs.csv")
fra <- read.csv("reconstructed_data/fra-bs.csv")
itl <- read.csv("reconstructed_data/itl-bs-ib.csv")
aus <- read.csv("reconstructed_data/aus-bs-ib.csv")


yields <- list(usa[1:250, ], gbr[1:250, ], jpn[1:250, ], cad[1:250, ], ger[1:250, ], fra[1:250, ], itl[1:250, ], aus[1:250,])
curves <- c("usa", "gbr", "jpn", "cad", "ger", "fra", "itl", "aus")
mats <- c(1, 3, 6, 12, 24, 60, 84, 120, 240, 360) 
lambdas <- seq(0.01, 0.1, by = 0.005)

```

```{r}
## primary test 
set.seed(999)
tmp <- mc_fit_end(yields=yields, lambdas=lambdas, cutoffs=c(4,8), reference="usa", curves=curves,mats=mats, X_trunc=TRUE, 
                  Xt_smooth=FALSE, smoother="bs", knot_count=6)

x1_synth <- arima.sim(model = list(ar=c(0.9)), 250)
x2_synth <- arima.sim(model = list(ar=c(-0.9)), 250)
xt_synth <- cbind(x1_synth, x2_synth)

tmp2 <- mc_fit_exo(yields=yields, lambdas=lambdas, Xt=xt_synth, cutoffs=c(4,8), reference="usa", curves=curves, mats=mats, 
                   Xt_smooth=TRUE, smoother="ns", knot_count=6)

```


```{r}
## testing 
source("yield_estimation/bl_single_curve.R")
source("yield_estimation/bl_feature_extract.R")

lambda_select_usa <- lambda_grid_search(lambdas, usa[1:250,], mats)
lambda_select_gbr <- lambda_grid_search(lambdas, gbr[1:250,], mats)
lambda_select_jpn <- lambda_grid_search(lambdas, jpn[1:250,], mats)
lambda_select_cad <- lambda_grid_search(lambdas, cad[1:250,], mats)


#microbenchmark(
#  func1 = lambda_grid_search(lambdas, usa[1:100,], mats), 
#  func2 = lambda_grid_search2(lambdas, usa[1:100,], mats), 
#  times = 100L  # Number of repetitions
#)

curves2 <- c("usa", "gbr", "jpn", "cad")

usa_curve <- bl_single_curve(lambda_select_usa, usa[1:250, ], c(4, 8), mats) # done 
gbr_curve <- bl_single_curve(lambda_select_gbr, gbr[1:250, ], c(4, 8), mats) # done 
jpn_curve <- bl_single_curve(lambda_select_jpn, jpn[1:250, ], c(4, 8), mats) # done 
cad_curve <- bl_single_curve(lambda_select_cad, cad[1:250, ], c(4, 8), mats) # done 

tsc_list <- transpose(setNames(list(usa_curve, gbr_curve, jpn_curve, cad_curve), curves2)) # done 
test_ccVARs <- blcc_cointegration(tsc_list, curves = curves2, reference = "usa") # done 

Xttest = blcc_build_Xt(test_ccVARs$cc_cspread, test_ccVARs$cc_ecm, trunc=TRUE)
Wtest = blcc_build_Wj(tsc_list$nsfit, mats) # done 
Htest <- bdiag(usa_curve$H, gbr_curve$H, jpn_curve$H, cad_curve$H) # done 
Ytest <- vecY(yields, curves, mats) # done 

blcc_build_Wj

Wtest$X01M
```

```{r}
source("yield_estimation/cr_core_estim.R")
source("yield_estimation/matrix_helpers.R")

test_BS0 <- blcc_fe(Xt=Xttest, Wt=Wtest, mats=mats, init="adaptive") # done 
ts <- tSigma_optim(test_BS0, Xttest) # done 

full_sigma_t <- sqrt_inv_build(ts$tSigma)
sqrt_sigma_t <- lapply(ts$tSigma, symmPSD_sqrt) # done 
sqrt_inv_sigma_t <- lapply(sqrt_sigma_t, solve) # done 

test_BS0$X06M$S0
```

```{r}
source("yield_estimation/bl_normalize.R")
Ptest <- bln_build_P(mats, curves) # done 
pY <- PY_full(Y$tY, P) # done  

yb <- bln_YB(pY$py, sqrt_inv_sigma_t) # done 
hb <- lapply(seq_along(sqrt_inv_sigma_t), function(dt) {
  bln_Hb(H, P, sqrt_inv_sigma_t[[dt]])
}) # done 

phi_hat <- bln_phi_hat(tsc_list$phi, mds) # done 
phib <-  bln_phi_BT(phi_hat, P, sqrt_inv_sigma_t) # done 

phic <- bln_phi_CT(phib, P) # done 
yc <- PY_full(yb, t(P)) # done, note transpose 

ycut <- cf_curve_cut(yc$py, curves, mats) # done 
phicut <- cf_phi_cut(phic, curves, mats) # done 

normalized <- bln_normalized_fit(ycut, phicut, curves, mats) # done 
```


```{r}
source("yield_estimation/bl_cross_estimation.R")

vyrs <- blce_rescale_yield(normalized$n_yield, sqrt_sigma_t, P, "tenor", time=ytime, curves=curves, mats=mats)
vyrs

```

```{r}
mc_fit_end <- function(yields, lambdas, cutoffs, reference, 
                       ECM_estim="ML", ECM_type="eigen", ECM_alpha=0.1, X_normalize=TRUE, X_trunc=FALSE,
                       CR_algo=zero_mean_covreg, CR_init="adaptive", Xt_smooth=FALSE, smoother=c("ns", "bs"), knot_count=5,
                       CR_maxiter=1000, CR_tol=1e-8, CR_Binit=NULL, CR_S0init=NULL, CR_verb=FALSE, CR_term=TRUE, 
                       curves, mats) {
  
  ## build maturity x tenor strings 
  mat_str <- sapply(mats, numeric_to_matname)
  mds <- as.vector(t(outer(curves, mat_str, paste, sep='.')))
  
  ## build vector yield embedding and permutation matrix  
  Y <- vecY(yields, curves, mats)   
  ytime <- Y[['time']]

  P <- bln_build_P(curves, mats)  
  pY <- PY_full(Y[['tY']], P)

  ## grid search lambda construction (to do: KF estimation) 
  curve_lambdas <- vapply(yields, function(x) { 
    lambda_grid_search(lambdas, x, mats)
    }, numeric(1) 
  )
  
  ## NS baseline estimation (no cross-curve) 
  bl_yields <- transpose(setNames(lapply(seq_along(yields), function(x) {
    bl_single_curve(curve_lambdas[x], yields[[x]], cutoffs, mats)
    }
  ), curves)) 
  
  ## residuals by tenor; within-curve full covariance  
  phi_hat <- bln_phi_hat(bl_yields$phi, mds) 
  W <- blcc_build_Wj(bl_yields$nsfit, mats) 
  H <- bdiag(bl_yields$H) 
  
  ## feature extraction 
  cc_ci_features <- blcc_cointegration(blsc_list=bl_yields, curves=curves, reference=reference, 
                                       estim=ECM_estim, type=ECM_type, alpha=ECM_alpha, normalize=X_normalize)
  Xt <- blcc_build_Xt(cc_ci_features$cc_cspread, cc_ci_features$cc_ecm, trunc=X_trunc) 
  
  if (Xt_smooth){
    kps <- fe_kp_quantile(time=ytime, knot_count=knot_count)
    Xt <- apply(Xt, 2, fe_xt_spline, time=ytime, spline_fit=smoother, knot_points=kps)
  }

  ## covariance regression and sigma estimation 
  cc_BS0_feature <- blcc_fe(Xt=Xt, Wt=W, mats=mats, covreg=CR_algo, init=CR_init, 
                            max_iter=CR_maxiter, tol=CR_tol, S0=CR_S0init, B=CR_Binit, verb=CR_verb, term=CR_term) 
    
  cc_Sigma <- tSigma_optim(BS0=cc_BS0_feature, X=Xt)
  
  full_sigma_t <- sqrt_inv_build(cc_Sigma$tSigma)
  sqrt_sigma_t <- full_sigma_t$sqrt
  sqrt_inv_sigma_t <- full_sigma_t$inverse

  ## breve components 
  yb <- bln_YB(pY[['py']], sqrt_inv_sigma_t) 
  phib <- bln_phi_BT(phi_hat, P, sqrt_inv_sigma_t)
  hb <- lapply(seq_along(sqrt_inv_sigma_t), function(dt) {
    bln_Hb(H, P, sqrt_inv_sigma_t[[dt]])
  })
  
  ## check components 
  phic <- bln_phi_CT(phib, P) 
  yc <- PY_full(yb, t(P))
  hc <- lapply(hb, function(hb_dt) t(P) %*% hb_dt %*% P)
  
  ## curve cuts  
  ycut <- cf_curve_cut(yc[['py']], curves, mats)
  phicut <- cf_phi_cut(phic, curves, mats)
  
  ## normalized 
  normalized <- bln_normalized_fit(ycut, phicut, curves, mats)
  ystar_tenor <- blce_rescale_yield(normalized[['n_yield']], sqrt_sigma_t, P, "tenor", time=ytime, curves=curves, mats=mats)
  ystar_curve <- blce_rescale_yield(normalized$n_yield, sqrt_sigma_t, P, "curve", time=ytime, curves=curves, mats=mats)
  
  return(list(
    tenor=ystar_tenor, 
    curve=ystar_curve, 
    curveECM=cc_ci_features[['cc_ecm']], 
    sigma_JT=cc_Sigma, 
    BS0=cc_BS0_feature))  
}

tmp <- mc_fit_end(yields=yields, lambdas=lambdas, cutoffs=c(4,8), reference="usa", curves=curves,mats=mats, X_trunc=TRUE, 
                  Xt_smooth=TRUE, smoother="bs", knot_count=12)
plot(tmp$curve$gbr.05Y, type='l', ylim=c(-5,5))

tmp$BS0$X01M$s_est
```

