---
title: "reconstruction_testing"
author: "Isaiah Katz"
date: "2025-11-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(microbenchmark)

source("data_formatting/dr_formatting.R")
source("core_formatting.R")
source("yield_estimation/bl_single_curve.R")

```


```{r}
## read-in raw unformatted data 
usa_raw <- read.csv("raw_data/USA_raw.csv")
gbr_raw <- read.csv("raw_data/GBR_raw.csv") 
jpn_raw <- read.csv("raw_data/JPN_raw.csv")
cad_raw <- read.csv("raw_data/CAD_raw.csv")

mats = c(1, 3, 6, 12, 24, 60, 84, 120, 240, 360)
fmats = c(1,2,3,6,9,12,24,60,72,84,120,240,360)

start_date <- "2000-01-01"
end_date <- "2000-01-30"

gbr_raw[1479:1500,]
```

```{r}
## validate format 
tmp <- dr_yield_format(gbr_raw, mats=mats, start_date=start_date, end_date=end_date)
```

```{r}
mats <- c(1, 3, 6, 12, 24, 60, 84, 120, 240, 360)
lambdas <- seq(0.01, 0.5, by=0.005)
init_date <- "2000-01-01"
end_date <- "2000-01-30"

## date range selection 
date_seq <- seq.Date(ymd(start_date), ymd(end_date), by = "day")
weekday_seq <- date_seq[weekdays(date_seq) %in% c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday")]

asdf <- dr_daily(data=tmp, reference=weekday_seq, threshold = 8)
```

```{r} 
source("data_formatting/dr_formatting.R")
source("core_formatting.R")

j <- dr_build_curve(asdf, c(1,2,3,6,9,12,24,60,72,84,120,240,360), build="spline", spline_method="natural")
j
jk <- dr_build_curve(asdf, c(1,2,3,6,9,12,24,60,72,84,120,240,360),build="parametric", par_method="nelson")
jk
jkl <- dr_build_curve(asdf, c(1,2,3,6,9,12,24,60,72,84,120,240,360), build="log")


lo <- lambda_grid_search(lambdas, jkl[1:20,], fmats)
ph <- bl_phi(lo, fmats)
as <- bl_NSbetas(jkl[1:20,], lo, ph$cross_phi, fmats)
```

```{r}
source("yield_estimation/bl_single_curve.R")

    #curve_phi <- bl_phi(lambda_select, mats), 
    #curve_betas <- bl_NSbetas(yields, lambda_select, curve_phi$cross_phi, mats), 
    #curve_nsfit <- bl_NSfit(curve_betas$m_yield, curve_phi$phi, curve_betas$NSbetas, lambda_select, mats), 
    #curve_H <- bl_bdiag_H(curve_nsfit$W, cutoffs, mats)), c("phi", "betas", "nsfit", "H")

sc_fit <- function(yields, mats, type = c("nelson", "svensson", "daily"), ts=TRUE,
                   lambdas = seq(from = 0.001, to = 1, length.out = 100), slambdas = NULL) {
  type = match.arg(type) 
  time <- yields[,1]; nt_yield <- yields[,-1] 

  if (type == "daily") {
    yield_estim <- sc_NSdaily(nt_yield, mats) 
    model_yields <- yield_estim[[1]] 
    model_betas <- yield_estim[[2]] 
  }
  else if (type == "nelson") {
    lambda <- lambda_grid_search(lambdas, yields, mats) 
    yield_estim <- sc_NSwindow(lambda, nt_yield, mats) 
    model_yields <- yield_estim[[1]]
    model_betas <- yield_estim[[2]]
    
  }
  else if (type == "svensson") {
    lambda1 = slambdas[1]; lambda2 = slambdas[2]
    yield_estim <- sc_Svensson(lambda1, lambda2, nt_yield, mats) 
    model_yields <- yield_estim[[1]]
    model_betas <- yield_estim[[2]]
  }
  
  if (!ts) {
    beta_dynamic <- NA 
  } 
  else {
    beta_dynamic <- apply(model_betas, 2, ar)
  }
  
  return(list(yields = model_yields, betas = model_betas, dynamic = beta_dynamic))
}
  

lambdas <- seq(from=0.001, to = 1, length.out=100)
fit_check <- sc_fit(jkl[1:20,], fmats, type="nelson" )
fit_check


qwer <- sc_NSdaily(jkl[1:20,-1], fmats)
dfj <- sc_NSwindow(lo, jkl[1:20, -1], fmats)
qwer$NSyields

sc_test <- sc_fit(yields=jkl[1:20,], mats=fmats, type="svensson", ts=TRUE, 
                  slambdas = c(2,3))

sc_test$dynamic$l4

```

```{r}
bl_phi2 <- function(lambda_optim, mats) {
  phi <- NS_loadings(lambda_optim, mats) 
  cross_phi <- solve(tcrossprod(phi)) %*% phi 
  return(list(phi = phi, cross_phi = cross_phi))
}

sven_phi <- function(lambda1, lambda2, mats) {
  phi <- Svensson_loadings(lambda1, lambda2, mats) 
  cross_phi <- solve(tcrossprod(phi)) %*% phi 
  return(list(phi = phi, cross_phi = cross_phi)) 
}

zxcv <- sc_Svensson(2, 3, jkl[1:20,-1], fmats)
```


